alias: LoRaWAN 0
description: ""
triggers:
  - domain: mqtt
    device_id: f979f033e7e0a37d0e321c566956be2a
    type: notification
    subtype: general
    trigger: device
conditions: []
actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: "{{ trigger.payload }}"
      title: LoRaWAN Adapter
mode: single
