alias: Data FromIoB LoraWAN 0
description: Empfängt Steuerbefehle von ioBroker via MQTT
triggers:
  - topic: lorawan_0/lorawan_0/lorawan_0_bridge_datafromiob/state
    trigger: mqtt
actions:
  - variables:
      payload: "{{ trigger.payload_json }}"
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'command'
                 and payload.entity_id.split('.')[0] == 'lock' }}
        sequence:
          - variables:
              cmd: "{{ payload.value | string | lower | trim }}"
          - action: |
              {% if cmd == 'lock' %}
                lock.lock
              {% elif cmd == 'unlock' %}
                lock.unlock
              {% elif cmd == 'open' %}
                lock.open
              {% else %}
                none
              {% endif %}
            target:
              entity_id: "{{ payload.entity_id }}"
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'temperature'
                 and payload.entity_id.split('.')[0] == 'climate' }}
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: "{{ payload.entity_id }}"
            data:
              temperature: "{{ payload.value | float }}"
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'humidity'
                 and payload.entity_id.split('.')[0] == 'humidifier' }}
        sequence:
          - action: humidifier.set_humidity
            target:
              entity_id: "{{ payload.entity_id }}"
            data:
              humidity: "{{ payload.value | int }}"
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'mode'
                 and payload.entity_id.split('.')[0] == 'humidifier' }}
        sequence:
          - action: humidifier.set_mode
            target:
              entity_id: "{{ payload.entity_id }}"
            data:
              mode: "{{ payload.value }}"
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.entity_id.split('.')[0] == 'light'
                 and payload.attribute is defined }}
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ payload.entity_id }}"
            data:
              "{{ payload.attribute }}": |
                {% if payload.attribute in ['brightness','transition'] %}
                  {{ payload.value | int }}
                {% else %}
                  {{ payload.value }}
                {% endif %}
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'command'
                 and payload.entity_id.split('.')[0] == 'cover' }}
        sequence:
          - variables:
              cmd: "{{ payload.value | string | lower | trim }}"
          - action: |
              {% if cmd == 'open' %}
                cover.open_cover
              {% elif cmd == 'close' %}
                cover.close_cover
              {% elif cmd == 'stop' %}
                cover.stop_cover
              {% else %}
                none
              {% endif %}
            target:
              entity_id: "{{ payload.entity_id }}"
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'position'
                 and payload.entity_id.split('.')[0] == 'cover' }}
        sequence:
          - action: cover.set_cover_position
            target:
              entity_id: "{{ payload.entity_id }}"
            data:
              position: "{{ payload.value | int }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ payload.entity_id is not defined }}"
        sequence:
          - variables:
              entity_id: "{{ payload.keys() | list | first }}"
              value: "{{ payload[entity_id] }}"
              domain: "{{ entity_id.split('.')[0] }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'button' }}"
                sequence:
                  - action: button.press
                    target:
                      entity_id: "{{ entity_id }}"
              - conditions:
                  - condition: template
                    value_template: >
                      {{ domain in
                      ['switch','light','input_boolean','humidifier'] }}
                sequence:
                  - action: |
                      {{ domain }}.turn_{{ 'on'
                        if value in [true,'true','on','1',1]
                        else 'off' }}
                    target:
                      entity_id: "{{ entity_id }}"
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'cover' }}"
                sequence:
                  - action: |
                      {% if value in ['open','on',true,'1',1] %}
                        cover.open_cover
                      {% elif value in ['stop','8',8] %}
                        cover.stop_cover
                      {% else %}
                        cover.close_cover
                      {% endif %}
                    target:
                      entity_id: "{{ entity_id }}"
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'lock' }}"
                sequence:
                  - action: |
                      {% if value in ['lock','on',true,'1',1] %}
                        lock.lock
                      {% else %}
                        lock.unlock
                      {% endif %}
                    target:
                      entity_id: "{{ entity_id }}"
  - action: system_log.write
    data:
      level: warning
      message: "ioBroker MQTT command processed: {{ trigger.payload }}"
mode: queued
max: 10
