alias: Data FromIoB LoraWAN 0
description: Empfängt Steuerbefehle von ioBroker via MQTT
triggers:
  - topic: lorawan_0/lorawan_0/lorawan_0_bridge_datafromiob/state
    trigger: mqtt
actions:
  - variables:
      payload: "{{ trigger.payload_json }}"
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute == 'temperature'
                 and payload.entity_id.split('.')[0] == 'climate' }}
        sequence:
          - target:
              entity_id: "{{ payload.entity_id }}"
            data:
              temperature: "{{ payload.value }}"
            action: climate.set_temperature
      - conditions:
          - condition: template
            value_template: |
              {{ payload.entity_id is defined
                 and payload.attribute is defined
                 and payload.value is defined }}
        sequence:
          - variables:
              entity_id: "{{ payload.entity_id }}"
              domain: "{{ payload.entity_id.split('.')[0] }}"
          - target:
              entity_id: "{{ entity_id }}"
            data:
              "{{ payload.attribute }}": "{{ payload.value }}"
            action: "{{ domain }}.turn_on"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ payload.entity_id is not defined }}"
        sequence:
          - variables:
              entity_id: "{{ payload.keys() | list | first }}"
              value: "{{ payload[entity_id] }}"
              domain: "{{ entity_id.split('.')[0] }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'button' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    action: button.press
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'text' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    data:
                      value: "{{ value | string }}"
                    action: text.set_value
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'input_text' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    data:
                      value: "{{ value | string }}"
                    action: input_text.set_value
              - conditions:
                  - condition: template
                    value_template: "{{ domain in ['switch','light','input_boolean'] }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    action: |
                      {{ domain }}.turn_{{ 'on'
                        if value in [true,'true','on','1',1]
                        else 'off' }}
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'number' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    data:
                      value: "{{ value }}"
                    action: number.set_value
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'input_number' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    data:
                      value: "{{ value }}"
                    action: input_number.set_value
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'input_select' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    data:
                      option: "{{ value }}"
                    action: input_select.select_option
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'cover' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    action: |
                      {{ 'cover.open_cover'
                        if value in [true,'open','on','1',1]
                        else 'cover.close_cover' }}
              - conditions:
                  - condition: template
                    value_template: "{{ domain == 'lock' }}"
                sequence:
                  - target:
                      entity_id: "{{ entity_id }}"
                    action: |
                      {{ 'lock.lock'
                        if value in [true,'lock','locked','on','1',1]
                        else 'lock.unlock' }}
  - data:
      level: warning
      message: "ioBroker MQTT command ignored: {{ trigger.payload }}"
    action: system_log.write
mode: queued
max: 10
