blueprint:
  name: From ioBroker – Entity → HA Control
  description: >
    Reagiert auf JSON-Steuerdaten aus einem ioBroker-LoRaWAN-Gerät
    (sensor.<instance>_datafromiob) und steuert HA-Entities abhängig vom Domain-Typ.
  domain: automation

  input:
    lorawan_device:
      name: LoRaWAN ioBroker Device
      description: Wähle die ioBroker-LoRaWAN-Instanz (lorawan.0, lorawan.1, …)
      selector:
        device:
          integration: iobroker

mode: queued
max: 10

trigger:
  - platform: state
    entity_id: >
      {{ device_entities(!input lorawan_device)
         | select('match', 'sensor\\..*_datafromiob$')
         | list
         | first }}

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state is not none
         and trigger.to_state.state not in ['unknown','unavailable',''] }}

action:
  - variables:
      payload: "{{ trigger.to_state.state | from_json }}"
      entity_id: "{{ payload.keys() | list | first }}"
      value: "{{ payload[entity_id] }}"
      domain: "{{ entity_id.split('.')[0] }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ domain in ['switch','light','input_boolean'] }}"
        sequence:
          - action: >
              {{ domain }}.turn_{{ 'on' if value in [true,'true','on','1',1] else 'off' }}
            target:
              entity_id: "{{ entity_id }}"

      - conditions:
          - condition: template
            value_template: "{{ domain == 'input_number' }}"
        sequence:
          - action: input_number.set_value
            target:
              entity_id: "{{ entity_id }}"
            data:
              value: "{{ value }}"

      - conditions:
          - condition: template
            value_template: "{{ domain == 'input_select' }}"
        sequence:
          - action: input_select.select_option
            target:
              entity_id: "{{ entity_id }}"
            data:
              option: "{{ value }}"

      - conditions:
          - condition: template
            value_template: "{{ domain == 'cover' }}"
        sequence:
          - action: >
              {{ 'cover.open_cover' if value in [true,'open','on','1',1] else 'cover.close_cover' }}
            target:
              entity_id: "{{ entity_id }}"

      - conditions:
          - condition: template
            value_template: "{{ domain == 'lock' }}"
        sequence:
          - action: >
              {{ 'lock.lock' if value in [true,'lock','locked','on','1',1] else 'lock.unlock' }}
            target:
              entity_id: "{{ entity_id }}"

  - action: system_log.write
    data:
      level: warning
      message: "ioBroker entity command ignored: {{ trigger.to_state.state }}"
