alias: DataToIOb_LoRaWAN_0_Periodic
description: Sendet alle markierten Entitäten gesammelt zyklisch an ioBroker
triggers:
  - trigger: time_pattern
    minutes: /10
actions:
  - action: mqtt.publish
    data:
      topic: lorawan_0/lorawan_0/lorawan_0_bridge_datatoiob/set
      retain: false
      payload: >
        {% set entity_labels = label_entities('ToIob') | default([]) %} {% set
        device_labels = label_devices('ToIob') | default([]) %} {% set ns =
        namespace(items={}) %}

        {% for s in states %}
          {% set eid = s.entity_id %}
          {% set dev = device_id(eid) %}
          {% set domain = eid.split('.')[0] %}
          {% set available = s.state not in ['unknown','unavailable'] %}

          {% if eid in entity_labels or (dev is not none and dev in device_labels) %}

            {# ---------- ATTRIBUTES ---------- #}
            {% set ns_attr = namespace(data={}) %}
            {% set exclude = [
              'friendly_name',
              'icon',
              'supported_color_modes',
              'effect_list',
              'device_class',
              'state_class',
              'unit_of_measurement'
            ] %}

            {% for k, v in s.attributes.items() %}
              {% if k not in exclude %}
                {% set ns_attr.data = ns_attr.data | combine({ k: v }) %}
              {% endif %}
            {% endfor %}

            {# ---------- CAPABILITIES ---------- #}
            {% set ns_caps = namespace(data={}) %}

            {# Light: supported_color_modes #}
            {% if s.attributes.supported_color_modes is defined %}
              {% set ns_caps.data = ns_caps.data | combine({
                "supported_color_modes": s.attributes.supported_color_modes
              }) %}
            {% endif %}

            {# Light: effect_list -> states mapping #}
            {% if s.attributes.effect_list is defined %}
              {% set states_map = namespace(data={}) %}
              {% for e in s.attributes.effect_list %}
                {% set states_map.data = states_map.data | combine({
                  (loop.index0 | string): e
                }) %}
              {% endfor %}
              {% set ns_caps.data = ns_caps.data | combine({
                "effects": {
                  "states": states_map.data
                }
              }) %}
            {% endif %}

            {# Cover: Commands exakt wie Change #}
        {% if domain == 'cover' and s.attributes.supported_features is defined %}
          {% set features = s.attributes.supported_features | int(0) %}
          {% set cmd_states = namespace(data={}) %}
        
          {% if (features // 1) % 2 == 1 %}
            {% set cmd_states.data = cmd_states.data | combine({ "1": "open" }) %}
          {% endif %}
        
          {% if (features // 2) % 2 == 1 %}
            {% set cmd_states.data = cmd_states.data | combine({ "2": "close" }) %}
          {% endif %}
        
          {% if (features // 8) % 2 == 1 %}
            {% set cmd_states.data = cmd_states.data | combine({ "8": "stop" }) %}
          {% endif %}
        
          {% if cmd_states.data %}
            {% set ns_caps.data = ns_caps.data | combine({
              "commands": {
                "states": cmd_states.data
              }
            }) %}
          {% endif %}
        {% endif %}

            {% set ns.items = ns.items | combine({
              eid: {
                "entity_id": eid,
                "domain": domain,
                "state": s.state,
                "available": available,

                "unique_id": s.attributes.unique_id | default(eid),
                "friendly_name": s.attributes.friendly_name | default(eid),
                "device_class": s.attributes.device_class | default(None),
                "state_class": s.attributes.state_class | default(None),
                "unit_of_measurement": s.attributes.unit_of_measurement | default(None),
                "last_changed": s.last_changed | string,
                "last_updated": s.last_updated | string,

                "attributes": ns_attr.data,
                "capabilities": ns_caps.data,

                "device": {
                  "id": dev,
                  "name": (
                    device_attr(dev, 'name_by_user')
                    or device_attr(dev, 'name')
                    or 'unknown'
                  ),
                  "manufacturer": device_attr(dev, 'manufacturer') | default('unknown'),
                  "model": device_attr(dev, 'model') | default('unknown')
                }
              }
            }) %}

          {% endif %}
        {% endfor %}

        {
          "version": "1.1.1",
          "discovery": true,
          "entities": {{ ns.items | tojson }}
        }
mode: queued
max: 2
